"""
Initial database set up.

Revision ID: 59e6d1acd9c
Revises: None
Create Date: 2015-10-19 18:09:17.771245
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e6d1acd9c'
down_revision = None


def upgrade():
    """Command auto generated by Alembic."""
    op.create_table(
        'roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('default', sa.Boolean(), nullable=True),
        sa.Column('permissions', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table(
        'teas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('category', sa.String(length=64), nullable=True),
        sa.Column('location', sa.String(length=64), nullable=True),
        sa.Column('image_url', sa.String(length=256), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('brewing_methods', sa.Text(), nullable=True),
        sa.Column('tasting_notes', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teas_name'), 'teas', ['name'], unique=True)
    op.create_table(
        'brewers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=64), nullable=True),
        sa.Column('username', sa.String(length=64), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.Column('password_hash', sa.String(length=128), nullable=True),
        sa.Column('confirmed', sa.Boolean(), nullable=True),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('location', sa.String(length=64), nullable=True),
        sa.Column('about_me', sa.Text(), nullable=True),
        sa.Column('member_since', sa.DateTime(), nullable=True),
        sa.Column('last_seen', sa.DateTime(), nullable=True),
        sa.Column('avatar_hash', sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brewers_email'), 'brewers', ['email'], unique=True)
    op.create_index(op.f('ix_brewers_username'), 'brewers', ['username'], unique=True)
    op.create_table(
        'pots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('brewed_at', sa.DateTime(), nullable=True),
        sa.Column('drank_at', sa.DateTime(), nullable=True),
        sa.Column('tea_id', sa.Integer(), nullable=True),
        sa.Column('brewer_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['brewer_id'], ['brewers.id'], ),
        sa.ForeignKeyConstraint(['tea_id'], ['teas.id'], ),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    """Command auto generated by Alembic."""
    op.drop_table('pots')
    op.drop_index(op.f('ix_brewers_username'), table_name='brewers')
    op.drop_index(op.f('ix_brewers_email'), table_name='brewers')
    op.drop_table('brewers')
    op.drop_index(op.f('ix_teas_name'), table_name='teas')
    op.drop_table('teas')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
